# Auto-generated by ai-web-tool to fix Windows asyncio subprocess support
# This runs before ANY other Python code on startup
import sys
if sys.platform == "win32":
    import asyncio
    asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
